# -*- mode: ruby -*-
# vi: set ft=ruby :
VM_LIST = {
  "iq-server" => {
    "ip" => "192.168.56.10",
    "cpus" => 2,
    "memory" => 8_192
  },
  "nexus" => {
    "ip" => "192.168.56.11",
    "cpus" => 8,
    "memory" => 16_384
  }
}

Vagrant.configure("2") do |config|
  VM_LIST.each do |hostname, opts|
    config.vm.define hostname do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = hostname
      node.vm.network :private_network, ip: opts["ip"]
      node.vm.provision "shell", path: "../provisioning/shell/ssh.sh", args: opts["ip"]

      node.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.cpus = opts["cpus"]
        vbox.memory = opts["memory"]
      end
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../provisioning/setup-ssh-key.yml"
    ansible.groups = {
      "all:children" => ["iq-server", "nexus"]
    }
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../provisioning/playbook-sonatype.yml"
    ansible.groups = {
      "group_iq" => ["iq-server"],
      "group_nexus" => ["nexus"],
      "all:children" => ["iq-server", "nexus"]
    }
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
  end
end
