---

- hosts: nexus-oss
  tasks:
    - name: "create new user for manage nexus"
      ansible.builtin.shell: |
        useradd -s /bin/bash -d {{ NEXUS_PATH }} -m nexus
        chmod +x {{ NEXUS_PATH }}
        echo "nexus ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/nexus
        sudo -u nexus -i
      become: true

    - name: "install nexus oss"
      ansible.builtin.shell: |
        sudo wget https://download.sonatype.com/nexus/3/nexus-3.80.0-06-linux-x86_64.tar.gz
        sudo tar xvzf nexus-*.tar.gz -C {{ NEXUS_PATH }}

    - name: "run nexus oss"
      ansible.builtin.shell: |
        cd {{ NEXUS_PATH }}/bin
        ./nexus start