---

- name: "[pre] install openjdk-17"
  ansible.builtin.apt:
    name: openjdk-17-jdk
  become: true

- name: "Ensure IQ_SERVER_PATH is executable (traversable)"
  ansible.builtin.file:
    path: "{{ IQ_SERVER_PATH }}"
    mode: "0755"
    state: directory
    recures: true
    owner: root
    group: root
  become: true

- name: "Install IQ Server"
  ansible.builtin.unarchive:
    src: "{{ IQ_SERVER_DOWNLOAD_URL }}"
    dest: "{{ IQ_SERVER_PATH }}"
    remote_src: yes
  become: true
  register: result

- name: "Print IQ Server insall succeed"
  ansible.builtin.debug:
    var: result
  when: result is succeeded