---

- hosts: all
  tasks:
    - name: "[pre] apt update"
      ansible.builtin.dnf:
        update_cache: yes
      become: true

    - name: "[pre] apt upgrade"
      ansible.builtin.dnf:
        upgrade: dist
      become: true

    - name: "[pre] install openjdk-17"
      ansible.builtin.dnf:
        name: openjdk-11-jdk
      become: true

- hosts: group_iq
  roles:
    - role: "./roles/sonatype/role-iq-server"

- hosts: group_nexus
  roles:
    - role: "./roles/sonatype/role-nexus"