---

- hosts: sonatype
  tasks:
    - name: "[pre] apt update"
      apt:
        update_cache: yes
      become: true

    - name: "[pre] apt upgrade"
      apt:
        upgrade: dist
      become: true

    - name: "[pre] install sonatype-iq-server"
      shell: |
        wget https://download.sonatype.com/clm/server/latest.tar.gz
        mkdir -p /opt/sonatype-iq-server
        tar xvzf nexus-iq-server*.tar.gz -C /opt/sonatype-iq-server/
        chown -R vagrant:vagrant /opt/sonatype-iq-server/
      become: true

    - name: "[pre] install java"
      apt:
        name: openjdk-17-jdk
      become: true

    - name: "run sonatype"
      shell: |
        java -jar nexus-iq-server-*.jar server config.yml 2> stderr.log
      become: true