---

- name: "Create directory for download IQ Server"
  ansible.builtin.file:
    path: "{{ IQ_SERVER_PATH }}"
    mode: "0755"
    state: directory
    owner: iqserver
    group: iqserver
  become: true

- name: "Install IQ Server"
  ansible.builtin.unarchive:
    src: "{{ IQ_SERVER_DOWNLOAD_URL }}"
    dest: "{{ IQ_SERVER_PATH }}"
    remote_src: yes
  become_user: iqserver
  become: true
  register: result

- name: "Print IQ Server install succeed"
  ansible.builtin.debug:
    var: result
  when: result is succeeded